### ISSUE TITLE
ERROR: Layer cgl-common is not compatible with the core layer

### ISSUE THREAD

**Issue by notanaka** [ubinux/yocto-ubinux#1]
I tried to build ubinux on fresh environment after installing Ubuntu 18.04 desktop on VirtualBox.
I met some errors while the build, but I report one thing in this report.
This is the first time to use github and yocto, so I don't know whether report format, contents and solution are correct.
After applying my following modification , the build can be continued and is not finished.

The error message of bitbake ubinux-all is here,

> ERROR: Layer cgl-common is not compatible with the core layer which only supports these series: zeus (layer is compatible with warrior)

So, I modified following configuration file.

> notanaka@notanaka-VirtualBox:~/git/build-ubinux-x86-64$ diff -u ../yocto-ubinux/meta-cgl/meta-cgl-common/conf/layer.conf{.org,}

```
--- ../yocto-ubinux/meta-cgl/meta-cgl-common/conf/layer.conf.org	2020-07-05 20:42:36.750548861 +0900
+++ ../yocto-ubinux/meta-cgl/meta-cgl-common/conf/layer.conf	2020-07-04 18:12:14.401103754 +0900
@@ -13,6 +13,6 @@
 
 LAYERDEPENDS_cgl-common = "core openembedded-layer networking-layer perl-layer filesystems-layer security selinux"
 
-LAYERSERIES_COMPAT_cgl-common = "warrior"
+LAYERSERIES_COMPAT_cgl-common = "zeus"
 
 require conf/distro/include/cgl_common_security_flags.inc

```

**Comment by wangmingyu84** [comment]
The update of meta-cgl upstream is very slow, so you can only modify this content manually. Your modification is right.

**Comment by notanaka** [comment]
I appreciate to get that my workaround was correct.
