### ISSUE TITLE
Build user permission is required for /yocto

### ISSUE THREAD

**Issue by notanaka** [ubinux/yocto-ubinux#2]
I tried to build ubinux on fresh environment after installing Ubuntu 18.04 desktop on VirtualBox.
I met some errors, but I report one thing in this time.
This is the first time to use github and yocto, so I don't know whether report format, contents and solution are correct.
After applying my following modification , the build can be continued and is not finished.

I used default conf/local.conf file(no modification).
The error message of bitbake ubinux-all is here,

>   File "/usr/lib/python3.6/os.py", line 220, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/yocto'

So, I created /yocto directory and change owner before starting bitbake ubinux-all as follows,

> notanaka@notanaka-VirtualBox:\~/git/build-ubinux-x86-64$ sudo mkdir /yocto
> notanaka@notanaka-VirtualBox:\~/git/build-ubinux-x86-64$ sudo chown notanaka /yocto

**Comment by wangmingyu84** [comment]
I'm sorry that we have not been able to reproduce the problem you mentioned. Please tell us what you did in the [3.2 Set up build environment] step of Readme, so that we can analyze the problem.

**Comment by notanaka** [comment]
Thank you for your confirmation.
Sorry, this error was occurred when I build ubinux on 100GB space and failed to build by file system full.
It might not be happen on enough free space.

**Comment by notanaka** [comment]
It doesn't seem free space problem.
I could reproduce the problem with enough free space.
Here is the error log and df result for your reference.

notanaka@notanaka-VirtualBox:~/build-ubinux-x86-64$ bitbake ubinux-all
NOTE: Your conf/bblayers.conf has been automatically updated.
WARNING: You have included the meta-openstack layer, but 'openstack' has not been enabled in your DISTRO_FEATURES. Some bbappend files and preferred version setting may not take effect. See the meta-openstack README for details on enabling openstack support.
Parsing recipes: 100% |#########################################| Time: 0:02:23
Parsing of 2063 .bb files complete (0 cached, 2063 parsed). 3118 targets, 51 skipped, 0 masked, 0 errors.
WARNING: No bb files matched BBFILE_PATTERN_spdxscanner '^/home/notanaka/yocto-ubinux/meta-spdxscanner/'
WARNING: No bb files matched BBFILE_PATTERN_multimedia-layer '^/home/notanaka/yocto-ubinux/meta-oe-zeus/meta-multimedia/'
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.44.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-18.04"
TARGET_SYS           = "x86_64-ubinux-linux"
MACHINE              = "ubinux-x86-64"
DISTRO               = "ubinux"
DISTRO_VERSION       = "2020.01"
TUNE_FEATURES        = "m64 core2"
TARGET_FPU           = ""
meta-ubinux          
meta                 
meta-poky            
meta-yocto-bsp       = "master:5d2d8eb1973288a77d6dc7eaf7bc9753cf2ba732"
meta-gplv2           = "zeus:0f4eecc000f66d114ad258fa31aed66afa292166"
meta-freescale       = "zeus:4af1824f3daa13bd2bceafe8de7f371b35e0dfce"
meta-filesystems     
meta-gnome           
meta-initramfs       
meta-networking      
meta-oe              
meta-python          
meta-webserver       
meta-xfce            
meta-perl            
meta-multimedia      = "zeus:0d16b31c3d96e0797d3335d44545412996c48c9a"
meta-cgl-common      = "master:fe28a226377697639d18a9c671dd5f9004be0ba0"
meta-cloud-services  
meta-openstack       = "zeus:b8c25f63ab9124fe911165205d17808b9a7dead0"
meta-virtualization  = "zeus:f4262ab75d36a06c528cc1630b48b817fb0acf8f"
meta-selinux         = "zeus:44d760413920ba440439b8bc7c2a71ca26cd7a2d"
meta-measured        = "master:a110355f087ce0ad1c90a3080878de3206fe0079"
meta-security        
meta-security-compliance = "zeus:27ddb455543b670097e252ba0d0ad5b7e4101748"
meta-qt5             = "zeus:432ad2aa6c3a13253fefc909faba368851d21fb1"
meta-swupdate        = "zeus:ae3be5af32322293e9118570dde8dec117a83222"
meta-linaro          = "master:14a8a62dca7a2c70d91578fc79e71911bc670253"
meta-spdxscanner     = "zeus:051a87f5e2396d63ab36d86f5d8a772fd868e490"

ERROR: Execution of event handler 'uninative_event_fetchloader' failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/os.py", line 210, in makedirs(name='/yocto/work001/common/downloads-ubinux202001/uninative', mode=511, exist_ok=False):
             try:
    >            makedirs(head, mode, exist_ok)
             except FileExistsError:
  File "/usr/lib/python3.6/os.py", line 210, in makedirs(name='/yocto/work001/common/downloads-ubinux202001', mode=511, exist_ok=False):
             try:
    >            makedirs(head, mode, exist_ok)
             except FileExistsError:
  File "/usr/lib/python3.6/os.py", line 210, in makedirs(name='/yocto/work001/common', mode=511, exist_ok=False):
             try:
    >            makedirs(head, mode, exist_ok)
             except FileExistsError:
  File "/usr/lib/python3.6/os.py", line 210, in makedirs(name='/yocto/work001', mode=511, exist_ok=False):
             try:
    >            makedirs(head, mode, exist_ok)
             except FileExistsError:
  File "/usr/lib/python3.6/os.py", line 220, in makedirs(name='/yocto', mode=511, exist_ok=False):
         try:
    >        mkdir(name, mode)
         except OSError:
PermissionError: [Errno 13] Permission denied: '/yocto'

ERROR: Command execution failed: Traceback (most recent call last):
  File "/home/notanaka/yocto-ubinux/bitbake/lib/bb/command.py", line 106, in runAsyncCommand
    commandmethod(self.cmds_async, self, options)
  File "/home/notanaka/yocto-ubinux/bitbake/lib/bb/command.py", line 598, in buildTargets
    command.cooker.buildTargets(pkgs_to_build, task)
  File "/home/notanaka/yocto-ubinux/bitbake/lib/bb/cooker.py", line 1483, in buildTargets
    bb.event.fire(bb.event.BuildStarted(buildname, ntargets), self.databuilder.mcdata[mc])
  File "/home/notanaka/yocto-ubinux/bitbake/lib/bb/event.py", line 215, in fire
    fire_class_handlers(event, d)
  File "/home/notanaka/yocto-ubinux/bitbake/lib/bb/event.py", line 122, in fire_class_handlers
    execute_handler(name, handler, event, d)
  File "/home/notanaka/yocto-ubinux/bitbake/lib/bb/event.py", line 94, in execute_handler
    ret = handler(event)
  File "/home/notanaka/yocto-ubinux/meta/classes/uninative.bbclass", line 49, in uninative_event_fetchloader
    bb.utils.mkdirhier(tarballdir)
  File "/home/notanaka/yocto-ubinux/bitbake/lib/bb/utils.py", line 723, in mkdirhier
    raise e
  File "/home/notanaka/yocto-ubinux/bitbake/lib/bb/utils.py", line 720, in mkdirhier
    os.makedirs(directory)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/yocto'


Summary: There were 3 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
notanaka@notanaka-VirtualBox:~/build-ubinux-x86-64$ df -k
Filesystem     1K-blocks    Used Available Use% Mounted on
udev            12440596       0  12440596   0% /dev
tmpfs            2492900    1540   2491360   1% /run
/dev/sda1      411796904 8171740 382637364   3% /
tmpfs           12464496       0  12464496   0% /dev/shm
tmpfs               5120       4      5116   1% /run/lock
tmpfs           12464496       0  12464496   0% /sys/fs/cgroup
/dev/loop0          3840    3840         0 100% /snap/gnome-system-monitor/127
/dev/loop2         46080   46080         0 100% /snap/gtk-common-themes/1440
/dev/loop5         56064   56064         0 100% /snap/core18/1668
/dev/loop3         91264   91264         0 100% /snap/core/8268
/dev/loop4        164096  164096         0 100% /snap/gnome-3-28-1804/116
/dev/loop1          1024    1024         0 100% /snap/gnome-logs/81
/dev/loop6          4352    4352         0 100% /snap/gnome-calculator/544
/dev/loop7         15104   15104         0 100% /snap/gnome-characters/399
tmpfs            2492896      28   2492868   1% /run/user/121
tmpfs            2492896      24   2492872   1% /run/user/1000
/dev/sr0           59206   59206         0 100% /media/notanaka/VBox_GAs_6.1.12
notanaka@notanaka-VirtualBox:~/build-ubinux-x86-64$

**Comment by wangmingyu84** [comment]
This problem occurs because the download directory is written as /yocto/xxx in the script setup_ubinux.sh. The download directory can be modified manually.

**Comment by notanaka** [comment]
Thanks, this problem was solved at https://github.com/ubinux/yocto-ubinux/issues/5#issuecomment-668013716
I confirmed DOWNLOADS directory was created under ~/build-ubinux-x86-64.
