### ISSUE TITLE
Required packages for ubinux build

### ISSUE THREAD

**Issue by notanaka** [ubinux/yocto-ubinux#3]
I tried to build ubinux on fresh environment after installing Ubuntu 18.04 desktop on VirtualBox.
I met some errors, but I report the last thing.
This is the first time to use github and yocto, so I don't know whether report format, contents and solution are correct.
I have just finished ubinux build with this additional packages and another 2 my reports.
I used default conf/local.conf file(no modification).

`$ sudo apt install git python chrpath g++ gawk gcc make texinfo python3-distutils`

Here is the last part of build log,

> Image CVE report stored in: /home/notanaka/git/build-ubinux-x86-64/tmp/deploy/images/ubinux-x86-64/ubinux-all-ubinux-x86-64-20200704091957.rootfs.cve
> NOTE: Tasks Summary: Attempted 16819 tasks of which 2 didn't need to be rerun and all succeeded.
> 
> Summary: There were 160 WARNING messages shown.
> 

About 250GB disk space is required for ubuntu descktop and ubinux.

**Comment by wangmingyu84** [comment]
Do you mean the space of ubinux is too large? Or any other issue?

**Comment by notanaka** [comment]
It is not a request and just notification for other users to build ubinux.
I failed to build it on 100GB free space before.
